//
//  MMAPIClientSessionDelegate.h
//
//  Copyright (c) 2013 SinnerSchrader Mobile. All rights reserved.
//

#import <Foundation/Foundation.h>
@class AFHTTPRequestOperation;

@protocol MMAPIClientSessionDelegate <NSObject>
@required
-(NSString*)sessionToken;

/**
 * Refreshes the session.
 * This method will be called by API calls that allow a retry in case the sessionToken has become invalid. The
 * actual call is generated by [delegate refreshSessionWithCompletionBlock:].
 * __Important:__ The error parameter of the completion block is guaranteed to be `nil` upon successful
 * completion.
 *
 * @param completionBlock The completionBlock that will be called after the API call has been completed.
 */
-(AFHTTPRequestOperation *)refreshSessionWithCompletionBlock:(void(^)(BOOL success))completionBlock;

@end
